class initialization
initializeArrays

LG2TagH1A initialize.
LG2DiffH1A initialize.
LG2IndexH1A initialize.
LG2CheckoutH1A initialize.
LG2TreeH1A initialize.
LG2NotesH1A initialize.
LG2TransportH12A initialize.
LG2CommitH1A initialize.
LG2SubmoduleH2A initialize.
LG2MergeH1A initialize.
LG2GraphH1A initialize.
LG2OdbH1A initialize.
LG2RepositoryH1A initialize.
LG2OidH1A initialize.
LG2PackH2A initialize.
LG2DiffH7A initialize.
LG2CloneH2A initialize.
LG2RemoteH6A initialize.
LG2BlobH1A initialize.
LG2ObjectH1A initialize.
LG2IndexerH1A initialize.
LG2RevwalkH1A initialize.
LG2ReflogH1A initialize.
LG2RefsH1A initialize.